# Generated by Django 3.2.7 on 2021-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activetripmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.IntegerField()),
                ('cycle_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=15)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
            ],
            options={
                'db_table': 't_active_trips',
            },
        ),
        migrations.CreateModel(
            name='Cyclemodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cycle_code', models.CharField(max_length=10)),
                ('operator_id', models.IntegerField()),
                ('hub_id', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
                ('is_charging', models.BooleanField()),
                ('battery_percentage', models.FloatField()),
                ('model_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_cycles',
            },
        ),
        migrations.CreateModel(
            name='Tripmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.IntegerField()),
                ('cycle_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=15)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
            ],
            options={
                'db_table': 't_trips',
            },
        ),
    ]
