# Generated by Django 3.2.7 on 2021-10-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cyclemodel',
        ),
    ]
