# Generated by Django 3.2.7 on 2021-10-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_auto_20211030_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activetripmodel',
            old_name='id',
            new_name='active_trip_id',
        ),
        migrations.RenameField(
            model_name='tripmodel',
            old_name='id',
            new_name='rip_id',
        ),
    ]
