# Generated by Django 3.2.7 on 2021-10-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_auto_20211030_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetripmodel',
            name='model_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='model_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
