# Generated by Django 3.2.7 on 2021-11-01 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_auto_20211031_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripdetailsmodel',
            fields=[
                ('trip_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('starting_lat', models.FloatField()),
                ('starting_long', models.FloatField()),
                ('ending_lat', models.FloatField()),
                ('ending_long', models.FloatField()),
                ('pathdetails', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
            ],
            options={
                'db_table': 't_trip_details',
            },
        ),
    ]
