# Generated by Django 3.2.7 on 2021-11-01 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0006_tripdetailsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetailsmodel',
            old_name='pathdetails',
            new_name='pathdetails_loc',
        ),
        migrations.AddField(
            model_name='tripdetailsmodel',
            name='active_trip_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tripdetailsmodel',
            name='pathdetails_long',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
