# Generated by Django 3.2.7 on 2021-11-01 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0007_auto_20211101_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetailsmodel',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
