# Generated by Django 3.1.8 on 2021-11-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0009_auto_20211101_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tripdetailsmodel',
        ),
    ]
