# Generated by Django 3.1.8 on 2021-11-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0010_delete_tripdetailsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripmodel',
            old_name='rip_id',
            new_name='trip_id',
        ),
    ]
