# Generated by Django 3.1.8 on 2021-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0011_auto_20211103_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripmodel',
            old_name='station_id',
            new_name='start_station_id',
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='end_station_id',
            field=models.IntegerField(null=True),
        ),
    ]
