# Generated by Django 3.2.7 on 2021-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managermodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('session_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_managers',
            },
        ),
        migrations.CreateModel(
            name='Managessionmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_manager_sessions',
            },
        ),
    ]
