# Generated by Django 3.2.7 on 2021-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermodel',
            name='hashed_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='managermodel',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
