# Generated by Django 3.2.7 on 2021-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20211023_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermodel',
            name='hashed_password',
            field=models.CharField(max_length=200),
        ),
    ]
