# Generated by Django 3.2.7 on 2021-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_managermodel_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermodel',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
    ]
