# Generated by Django 3.2.7 on 2021-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_alter_managermodel_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managessionmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_manager_sessions',
            },
        ),
    ]
