# Generated by Django 3.2.7 on 2021-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20211023_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermodel',
            name='hashed_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='managessionmodel',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
    ]
