# Generated by Django 3.2.7 on 2021-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operatormodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('session_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_operators',
            },
        ),
        migrations.CreateModel(
            name='Operatsessionmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_operator_sessions',
            },
        ),
        migrations.CreateModel(
            name='Stationmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operator_id', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('serialised_plan', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 't_stations',
            },
        ),
    ]
