# Generated by Django 3.2.7 on 2021-10-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_alter_operatsessionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatsessionmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
