# Generated by Django 3.2.7 on 2021-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_operatsessionmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatsessionmodel',
            old_name='customer_id',
            new_name='operator_id',
        ),
        migrations.AlterField(
            model_name='operatormodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='operatormodel',
            name='session_id',
            field=models.IntegerField(null=True),
        ),
    ]
