# Generated by Django 3.2.7 on 2021-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_alter_stationmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='operator_id',
            field=models.IntegerField(null=True),
        ),
    ]
