# Generated by Django 3.2.7 on 2021-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_alter_stationmodel_operator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cycle_code', models.CharField(max_length=10)),
                ('operator_id', models.IntegerField(null=True)),
                ('station_id', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
                ('is_charging', models.CharField(max_length=10)),
                ('battery_percentage', models.FloatField()),
                ('model_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_cycles',
            },
        ),
    ]
