# Generated by Django 3.2.7 on 2021-10-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_cyclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errormodel',
            fields=[
                ('error_code', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('error_message', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 't_errors',
            },
        ),
    ]
