# Generated by Django 3.2.7 on 2021-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_errormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormodel',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
