# Generated by Django 3.2.7 on 2021-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0009_alter_errormodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormodel',
            name='error_message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
