# Generated by Django 3.2.7 on 2021-10-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0010_auto_20211025_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationmodel',
            old_name='id',
            new_name='station_id',
        ),
        migrations.RemoveField(
            model_name='stationmodel',
            name='operator_id',
        ),
    ]
