# Generated by Django 3.2.7 on 2021-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0011_auto_20211026_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statusmodel',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 't_repair_status',
            },
        ),
        migrations.RenameField(
            model_name='cyclemodel',
            old_name='id',
            new_name='cycle_id',
        ),
        migrations.RemoveField(
            model_name='cyclemodel',
            name='cycle_code',
        ),
        migrations.RemoveField(
            model_name='cyclemodel',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='cyclemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='cyclemodel',
            name='status_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
