# Generated by Django 3.2.7 on 2021-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0012_auto_20211026_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclemodel',
            name='battery_percentage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemodel',
            name='is_charging',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemodel',
            name='model_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemodel',
            name='status_id',
            field=models.IntegerField(null=True),
        ),
    ]
