# Generated by Django 3.1.8 on 2021-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('favorite_station_id', models.IntegerField(null=True)),
                ('active_trip_id', models.IntegerField(null=True)),
                ('credits', models.IntegerField(default=10)),
                ('session_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_customers',
            },
        ),
        migrations.CreateModel(
            name='Custsessionmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_customer_sessions',
            },
        ),
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('trip_id', models.IntegerField(null=True)),
                ('transaction_time', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='credits', max_length=20)),
                ('charge', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('card_number', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 't_payments',
            },
        ),
    ]
