# Generated by Django 3.2.7 on 2021-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('hashed_password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('post_code', models.CharField(max_length=10)),
                ('security_question', models.CharField(max_length=150)),
                ('security_answer', models.CharField(max_length=100)),
                ('favorite_station_id', models.IntegerField()),
                ('active_trip_id', models.IntegerField()),
                ('email_verified', models.IntegerField()),
                ('session_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_customers',
            },
        ),
        migrations.CreateModel(
            name='Custsessionmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_customer_sessions',
            },
        ),
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('transaction_time', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 't_payments',
            },
        ),
    ]
