# Generated by Django 3.1.8 on 2021-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customodel',
            name='credits',
            field=models.FloatField(default=10.0),
        ),
    ]
