# Generated by Django 3.2.7 on 2021-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211026_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customodel',
            name='email_verified',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
