# Generated by Django 3.2.7 on 2021-10-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211030_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customodel',
            name='credits',
            field=models.IntegerField(default=10),
        ),
    ]
