# Generated by Django 3.2.7 on 2021-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customodel_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='card_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(default='credits', max_length=20),
        ),
    ]
