# Generated by Django 3.2.7 on 2021-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20211031_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='trip_id',
            field=models.IntegerField(null=True),
        ),
    ]
