# Generated by Django 3.1.8 on 2021-11-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_paymentmodel_trip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customodel',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customodel',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='customodel',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='customodel',
            name='security_question',
        ),
    ]
