# Generated by Django 3.1.8 on 2021-11-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20211102_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customodel',
            name='favorite_station_id',
            field=models.IntegerField(null=True),
        ),
    ]
